version: "3.8"
services:
  jenkins:
       image: jenkins/jenkins:lts
       privileged: true
       user: root
       expose:
         - "8080"
         - "50000"
       volumes:
         - /home/ec2-user/jenkins_compose/jenkins_configuration:/var/jenkins_home #Change user home direcroty as per OS
         # Maps dir on OS to:Dir on container
         - /var/run/docker.sock:/var/run/docker.sock # If want to run container witihin container
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: # If Jenkins service is not up then nginx will not work.
      - jenkins
    ports:
      - "4000:4000"  
